name: Test and Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Setup Node
        uses: ./.github/actions/checkout-and-setup
      - run: npm test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Setup Node
        uses: ./.github/actions/checkout-and-setup
      - run: npm run build
